3rd ubuntu test after reworking the env script stuff...

diff --git a/build-cac-enabled-git b/build-cac-enabled-git
--- a/build-cac-enabled-git
+++ b/build-cac-enabled-git
@@ -7,7 +7,7 @@
 # -Lots of trial-and-error/debugging.
 # Date: 09 March 2015
 # --TODO--
-VERSION=0.9.4
+VERSION=0.9.5
 # Starting cwd is base of operations.
 # TODO: Check to be sure it seems to contain the package.
 Basedir=$PWD
@@ -41,6 +41,7 @@ declare -A Opts=(
 	[ca-bundle-in]=http://curl.haxx.se/ca/cacert.pem
 	[ca-bundle-out]=~/ca-bundle-plus-dod-root.pem
 	[openssl-conf]=~/pkcs11-openssl.cnf
+	[env-script]=~/cac-enabled-git-env.sh
 )
 
 declare -a Steps=(
@@ -168,46 +169,49 @@ show_help() {
 	    Cygwin "Web" package).
 	  Linux users:
 	    This script assumes you have a standard Linux build toolchain, as well as
-		the following libraries:
-		  nss
-		  openssl
+		the following libraries or suitable equivalents:
+	    Note: Exact package names may vary from one distribution to the next.
+	      openssl libnss libssl-dev
+	      git autoconf automake m4 libtool
+	      gettext libexpat1-dev
+	      libpcsclite-dev
 
 	Running the script:
-	  1. Open the default Cygwin shell (runs an instance of Bash).
+	  1. Open a shell with access to Bash.
 	  2. Create an empty directory anywhere you like.
 	  3. cd to the directory created in step 2, and run this script.
 
-	  Note: The Cygwin terminal's buffer is probably not sufficiently large to
-	  hold all of the output generated by the script. If you wish to monitor the
-	  script's progress real-time, but capture all output in a logfile, you could
- 	  do something like this...
-	      ./setup.sh [OPTIONS] |& tee \~/tmp/setup.log
+	  Note: The terminal's buffer may not be sufficiently large to hold all of
+	  the output generated by the script. If you wish to monitor the script's
+	  progress real-time, but capture all output in a logfile, you could do
+	  something like this...
+	      ./$prog [OPTIONS] |& tee ./setup.log
 
 	  Alternatively, if you wish to see only stderr, redirecting stdout to a
 	  file for inspection at a later time...
-	      ./setup.sh [OPTIONS] >\~/tmp/setup.log
+	      ./$prog [OPTIONS] > ./setup.log
 
 	Output:
 	  Upon successful termination of this script, you should have a CAC-aware Git
-	  in your path (/usr/local/bin), and a startup script in /etc/profile.d, which
-	  automatically makes the environment changes needed to use the CAC-aware Git
-	  each time you start a shell.
+	  in your path (/usr/local/bin). Additionally, this script will attempt to
+	  add \`source' commands to several of your startup scripts to ensure that
+	  the environment variables needed to use the CAC-aware Git are set in both
+	  login and non-login interactive shells.
 
-	  Note: If you wish to inhibit loading the PKCS11 engine temporarily, you have
-	  several options:
+	  Note: If you wish to inhibit loading the PKCS#11 engine temporarily, you
+	  have several options:
 	    1. Set environment variable INHIBIT_CAC_ENABLED_GIT=1 to prevent the env
-	       vars from being defined each time you start a Cygwin shell.
-	    2. Run disable_cac_aware_git from within your current Cygwin bash shell.
+	       vars from being defined each time you start a shell.
+	    2. Run disable_cac_aware_git from within your current shell.
 	       Note: There's a matching enable_cac_aware_git should you wish to
 	       re-enable.
 
-	  Note: This script installs the default (non-CAC-aware) Cygwin Git in
-	  /usr/bin; thus, a more definitive way to disable the CAC customizations is
-	  simply to use the default git in /usr/bin instead of the customized git in
-	  /usr/local/bin. To facilitate this, the startup script also creates...
-	    ncgit
-	  ...as an alias to the default Git.
-
+	  Note: This script leaves the default (non-CAC-aware) Git in its default
+	  location (typically /usr/bin); thus, a more definitive way to disable the
+	  CAC customizations is to adjust your PATH to ensure that the default Git is
+	  is found first. Additionally, the aforementioned startup script creates...
+	      ncgit
+	  ...(non-CAC git) as an alias to /usr/bin/git.
 	eof
 }
 error() {
@@ -218,17 +222,15 @@ error() {
 	fi
 	echo >&2 "$@"
 	if [[ $usage == yes ]]; then
-		# Pass error along to usage for display.
-		usage "$@"
+		usage
 	fi
-	# TODO: Consider adding an error code option.
 	exit 1
+}
+warn() {
+	echo >&2 "Warning: $@"
 }
 list_steps() {
 	cat <<-eof
-	install_cygwin (Windows Only - unconditional prerequisite check)
-	    Install Cygwin packages for NSS and OpenSSL, as well as some packages that
-	    will be required by the build process.
 	download_source
 	    Download source code for several OpenSC libraries and tools, as well as
 	    the source for cURL and Git (both of which we'll be patching and
@@ -260,13 +262,9 @@ list_steps() {
 	build_git
 	    Build the modified Git
 	install_env_script
-	    Install startup script /etc/profile.d/cac-enabled-git.sh, whose purpose is
-	    to ensure that the environment variables required for proper operation are
-	    set automatically each time a Cygwin shell is started.
-	    Note: To disable this mechanism at a later date, you can either...
-	      -Set env var INHIBIT_CAC_ENABLED_GIT=1 (persistent change)
-	      -Run disable_cac_aware_git from a running Cygwin shell (disables in
-	       current shell only, and can be re-enabled with enable_cac_aware_git).
+		Install an env var script (and if possible, links thereto in several
+		startup scripts), to ensure the environment needed to run CAC-enabled Git
+	    in your shells.
 	eof
 }
 # Processes a ~ (alone) or a ~/ at head of input path, replacing with `$HOME/'.
@@ -372,11 +370,10 @@ detect_system() {
 # Assumption: errexit option has not yet been enabled.
 process_opt() {
 	# TODO: Consider a different way, which would handle defaults.
-	# TODO: Perhaps put these in array, at least...
 	local -a longs=(
 		"help" version list-steps
 		start-step: end-step: skip-steps: only-steps:
-		card-id: ca-bundle-in: ca-bundle-out: openssl-conf:
+		card-id: ca-bundle-in: ca-bundle-out: openssl-conf: env-script:
 		skip-cygwin-x no-install no-execute)
 	local shorts='s:e:'
 	# getopt idiosyncrasy: 1st arg specified to a long opt intended to be used to build an array can lose the 1st arg if
@@ -431,6 +428,10 @@ process_opt() {
 			--ca-bundle-in) Opts[ca-bundle-in]=$1; shift;;
 			--ca-bundle-out) Opts[ca-bundle-out]=$1; shift;;
 			--openssl-conf) Opts[openssl-conf]=$1; shift;;
+			--env-script)
+				# Silently convert - to /dev/null
+				Opts[env-script]=${Opts[env-script]/-/'/dev/null'}
+				shift;;
 			--skip-cygwin-x)
 				Opts[skip-cygwin-x]=yes;;
 			--no-install)
@@ -443,7 +444,12 @@ process_opt() {
 }
 # React to values of certain options, now that all have been set and detection is complete.
 post_process_opt() {
-	:
+	# Abort early if we can't write the env script and user hasn't disabled this.
+	if [[ ${Opts[env-script]} != /dev/null && -e ${Opts[env-script]} ]]; then
+		error "Refusing to overwrite env script file \`${Opts[env-script]}'. Either remove the file before running this" \
+			"script, or specify a different path with the --env-script option. (Note that you can prevent the script from" \
+			"being written with --env-script=- or --env-script=/dev/null.)"
+	fi
 }
 detect_cac_card() {
 	if [[ -n $Card_id ]]; then
@@ -464,8 +470,8 @@ detect_cac_card() {
 
 		# TODO: Allow user to insert and retry.
 		if [[ -z $Card_id ]]; then
-			echo 2>&1 "Warning: Unable to detect CAC card. Insert now if you wish to continue."
-			echo 2>&1 "Continue? (y/[n])"
+			echo >&2 "Warning: Unable to detect CAC card. Insert now if you wish to continue."
+			echo >&2 "Continue? (y/[n])"
 			read ans
 			if [[ $ans != [yY] ]]; then
 				return 1
@@ -560,16 +566,15 @@ do_prereq_ubuntu() {
 	# TODO: Add libiconv-dev
 	# TODO: Consider adding gcc, make, etc..., but should already be there...
 	local -a pkgs=(
-		git
-		autoconf automake m4
-		gettext libtool
-		openssl libssl-dev
+		openssl libnss libssl-dev
+		git autoconf automake m4 libtool
+		gettext libexpat1-dev
 		libpcsclite-dev
-		libexpat1-dev
 	)
 	log --ts "Installing ubuntu prerequisite packages: ${pkgs[@]}..."
 	# Assumption: Script is running with root privileges (e.g., sudo).
-	apt-get install "${pkgs[@]}"
+	# Note: Suppress tty prompt.
+	apt-get install -y "${pkgs[@]}"
 	log --ts "Finished installing ubuntu prerequisite packages..."
 }
 do_prereq_linux() {
@@ -800,10 +805,86 @@ build_git() {
 	# Note: Git has no configure script.
 	NO_R_TO_GCC_LINKER=1 CURLDIR=/usr/local make -C git prefix=/usr/local all ${Opts[no-install]:-install}
 }
-install_env_script() {
-	# TODO: Any reason to make this configurable?
+# Does input file contain a command that would dot-source the env script?
+file_contains_env_link() {
+	# Note: Permit (but don't require) quotes around the name.
+	# Possible TODO: When head of env-script is expanded `~', perhaps ensure that it's written to file unexpanded. For
+	# now, assuming always expanded.
+	grep -q '^[[:space:]]*\(\.\|source\)[[:space:]]\+'"[\"']\\?${Opts[env-script]}[\"']\\?"'\>' < "$1"
+}
+# Append to the input file a command to dot-source the env script.
+add_env_link_to_file() {
+	echo ". '${Opts[env-script]}'" >> "$1"
+}
+# Taking into account Bash startup logic... Add links (. <env-script>) to startup scripts to ensure that the env vars
+# are created in both login and non-login interactive shells.
+# Logic: If none of the shell startup files in a group exist, create the highest priority one.
+# Rationale: If we picked one other than 1st, things would stop working when user subsequently created a file
+# with higher precedence.
+# Possible TODO: Adding the link to all 3 scripts might be a bit more robust, and wouldn't really be harmful,
+# given that only one of the 3 is ever sourced (unless user sources one from the other). Hmm...
+# Assumption: User will be using bash (not sh).
+add_env_script_links() {
+	local problem=
+	# prioritized lists of files in the 2 groups (login, non-login interactive)
+	local -a login=(~/.bash_profile ~/.bash_login ~/.profile)
+	local -a inter=(~/.bashrc)
+	local ary
+	for ary in login inter; do
+		# A bit of kludgery to emulate multi-dim arrays.
+		local idx="$ary[@]"
+		local added=
+		local -i pass
+		for pass in 1 2; do
+			local f
+			for f in "${!idx}"; do
+				# Stop after 1st one found...
+				if ((pass == 1)); then
+					# pass 1 - consider only existing files
+					if [[ -r $f ]]; then
+						if file_contains_env_link "$f"; then
+							added=yes
+						elif [[ -w $f ]]; then
+							add_env_link_to_file "$f"
+							added=yes
+						fi
+					fi
+				else
+					# pass 2 - create highest priority file we can
+					if [[ ! -e $f || -w $f ]]; then
+						add_env_link_to_file "$f"
+						added=yes
+					fi
+				fi
+				if [[ -n $added ]]; then break 2; fi
+			done
+		done
+		if [[ -z $added ]]; then
+			warn "Unable to add env script link for $([[ $ary == login ]] && echo "login" || echo "interactive") shells."
+			problem=yes
+		fi
+	done
+	if [[ -n $problem ]]; then
+		cat >&2 <<-eof
+		Warning: Env settings have been added to...
+		    ${Opts[env-script]}
+		...but I could not add a command to source it to one or more startup file(s).
+		Either add the commands manually: e.g.,
+		    . ${Opts[env-script]}
+		...or re-run this script with option --start-step=install_env_script after
+		ensuring that at least 1 startup script in each of the following groups is
+		modifiable:
+		    1) ${login[@]}
+		    2) ${inter[@]}
+		eof
+	fi
+}
+write_env_script() {
+	if [[ ${Opts[env-script]} != /dev/null ]]; then
+		return 0
+	fi
 	# TODO: Consider putting the cac id detection there also (in case slot id moves)...
-	cat <<eof >/etc/profile.d/cac-enabled-git.sh
+	cat <<eof >"${Opts[env-script]}"
 #! /bin/bash
 enable_cac_aware_git() {
 	# Add environment vars needed for CAC-enabled Git
@@ -821,7 +902,7 @@ enable_cac_aware_git() {
 	# defaulting to the console-based prompt.
 	# Note: The inhibit could also be accomplished by setting GIT_ASKPASS to empty string, but that would impact
 	# non-CAC Git(s) as well, and there may be reasons we want it inhibited only for the CAC-aware Git (e.g, you're
-	# goint to have to enter PKCS#11 pin at tty anyways).
+	# going to have to enter PKCS#11 pin at tty anyways).
 	export GIT_INHIBIT_ASKPASS=yes
 }
 disable_cac_aware_git() {
@@ -835,12 +916,17 @@ disable_cac_aware_git() {
 # var. To disable/re-enable in a running shell, he can use the following functions:
 #     enable_cac_aware_git
 #     disable_cac_aware_git
-if [[ \$(uname -o) == Cygwin && -z \$INHIBIT_CAC_ENABLED_GIT ]]; then
-	enable_cac_aware_git
-fi
+[ -z \$INHIBIT_CAC_ENABLED_GIT ] && enable_cac_aware_git
 # As a convenience, provide an alias to "non-CAC-aware" git.
 alias ncgit=/usr/bin/git
 eof
+}
+install_env_script() {
+	# Don't try to install if user explicitly disabled.
+	if [[ ${Opts[env-script]} != /dev/null ]]; then
+		write_env_script
+		add_env_script_links
+	fi
 }
 
 detect_system
@@ -856,4 +942,4 @@ set -e
 trap on_exit EXIT
 run
 
-# vim:ts=4:sw=4:tw=120
+# vim: ts=4:sw=4:tw=120
